Create DATABASE FastEval;


CREATE TABLE BAREME (
	ID_BAREME serial NOT NULL,
	BONNE_REP FLOAT, 
	MAUVAISE_REP FLOAT, 
	ABSENCE_REP FLOAT, 
	NON_RECONNAISSANCE_REP FLOAT,
	CONSTRAINT PK_Bareme PRIMARY KEY(ID_BAREME)
);


CREATE TABLE PARAMETRES( ID_PARAMETRES SERIAL NOT NULL, 
`NAME` VARCHAR(60) NOT NULL, 
`VALUE` VARCHAR(50) NOT NULL, 
CONSTRAINT PK_PARAMETRES PRIMARY KEY (ID_PARAMETRES));


Insert into PARAMETRES (NAME, VALUE) values ('bonne_reponse', '1');
Insert into PARAMETRES (NAME, VALUE) values ('mauvaise_reponse', '-1');
Insert into PARAMETRES (NAME, VALUE) values ('absence_reponse', '0');
Insert into PARAMETRES (NAME, VALUE) values ('non_reconnaissance_reponse', '0');

CREATE TABLE EVALUATION
   (
    ID_EVALUATION serial NOT NULL  ,
    `TYPE` varchar(2) NOT NULL  ,
    NB_ETUDIANT INT NULL  ,
    DATE_EVALUATION DATE NULL  ,
	ID_BAREME INTEGER NOT NULL,
	CONSTRAINT PK_EVALUATION PRIMARY KEY (ID_EVALUATION)
   );
 
ALTER TABLE EVALUATION ADD FOREIGN KEY (ID_BAREME) REFERENCES BAREME(ID_BAREME) ON DELETE RESTRICT ON UPDATE RESTRICT;
   
   
 CREATE TABLE SUJET
   (
    ID_SUJET serial NOT NULL  ,
    LIBELLE varchar(30) NOT NULL  ,
    CHEMIN VARCHAR(200) NOT NULL  ,
	CORRECTION VARCHAR(80) ,
	NUM_SUJET INT(10),
	ID_EVALUATION INTEGER NOT NULL ,
	CONSTRAINT PK_SUJET PRIMARY KEY (ID_SUJET)
   );
ALTER TABLE SUJET ADD FOREIGN KEY (ID_EVALUATION) REFERENCES EVALUATION(ID_EVALUATION) ON DELETE RESTRICT ON UPDATE RESTRICT;


 CREATE TABLE PROMOTION
   (
    ID_PROMOTION serial NOT NULL  ,
	NOM_PROMOTION VARCHAR(30) NOT NULL,
	DATE_PROMOTION DATE NOT NULL,
	CONSTRAINT PK_PROMOTION PRIMARY KEY (ID_PROMOTION)
	);
   
 CREATE TABLE ETUDIANT
   (
    ID_ETUDIANT serial NOT NULL  ,
	ID_PROMOTION INTEGER NOT NULL,
	CONSTRAINT PK_ETUDIANT PRIMARY KEY (ID_ETUDIANT, ID_PROMOTION)
	);
	
ALTER TABLE ETUDIANT ADD FOREIGN KEY (ID_PROMOTION) REFERENCES PROMOTION(ID_PROMOTION) ON DELETE RESTRICT ON UPDATE RESTRICT;
   
 CREATE TABLE ETUDIANT_NOMINATIF
   (
    ID_ETUDIANT INTEGER NOT NULL  ,
	ID_PROMOTION INTEGER NOT NULL,
    NUM_ETUDIANT VARCHAR(30) NOT NULL  ,
    NOM_ETUDIANT VARCHAR(60) NULL  ,
    PRENOM_ETUDIANT VARCHAR(30) NULL  ,
	CONSTRAINT PK_ETUDIANT_NOMINATIF PRIMARY KEY (ID_ETUDIANT, ID_PROMOTION)
   );

 ALTER TABLE ETUDIANT_NOMINATIF ADD FOREIGN KEY (ID_ETUDIANT, ID_PROMOTION) REFERENCES ETUDIANT (ID_ETUDIANT, ID_PROMOTION) ON DELETE RESTRICT ON UPDATE RESTRICT;

 CREATE TABLE ETUDIANT_ANONYME
   (
    ID_ETUDIANT INTEGER NOT NULL  ,
	ID_PROMOTION INTEGER NOT NULL,
    NUM_ANONYMAT VARCHAR(30) NOT NULL  ,
	CONSTRAINT PK_ETUDIANT_ANONYME PRIMARY KEY (ID_ETUDIANT, ID_PROMOTION)
   );
   
ALTER TABLE ETUDIANT_ANONYME ADD FOREIGN KEY (ID_ETUDIANT, ID_PROMOTION) REFERENCES ETUDIANT (ID_ETUDIANT, ID_PROMOTION) ON DELETE RESTRICT ON UPDATE RESTRICT;
   
  CREATE TABLE NOTE
   (
    ID_EVALUATION INTEGER NOT NULL  ,
	ID_ETUDIANT INTEGER NOT NULL,
	ID_PROMOTION INTEGER NOT NULL,
	NOTE FLOAT NOT NULL,
	CONSTRAINT PK_NOTE PRIMARY KEY (ID_EVALUATION, ID_ETUDIANT, ID_PROMOTION)
   );
   
ALTER TABLE NOTE ADD FOREIGN KEY (ID_EVALUATION) REFERENCES EVALUATION (ID_EVALUATION) ON DELETE RESTRICT ON UPDATE RESTRICT;
ALTER TABLE NOTE ADD FOREIGN KEY (ID_ETUDIANT, ID_PROMOTION) REFERENCES ETUDIANT (ID_ETUDIANT, ID_PROMOTION) ON DELETE RESTRICT ON UPDATE RESTRICT;
  
   
